name: eski
description: The offical dart port of the Eski Server!
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.1
  events_emitter: ^0.5.2
  faker: ^2.1.0
  flat: ^0.4.1
  logging: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
